# Generated by Django 3.2.5 on 2021-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Print_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtracker',
            name='total_print_time',
        ),
        migrations.AddField(
            model_name='printtracker',
            name='total_hours_printed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printtracker',
            name='total_minutes_printed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printtracker',
            name='date_of_print',
            field=models.DateField(),
        ),
    ]
