# Generated by Django 3.2.5 on 2021-07-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print_tracker", "0002_remove_printtracker_print_successful"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printtracker",
            name="stl_file",
        ),
        migrations.AddField(
            model_name="printtracker",
            name="gcode_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
